sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFSC14oGGXRndm7T1q5
    access-key-secret: 11IRQUEXKua6dsA00DIRcNpt9nmSVC
    bucket-name: web-tlias-lyq-w
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx2051a2da4cbfc2b8
    secret: 2dca76be2369ed5ecc1ded0b9f879666